# Generated by Django 3.1.4 on 2021-05-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='EmotionPlaylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.emotionplaylist'),
        ),
    ]
